/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCardSizesRouteImport } from './routes/_authenticated/card-sizes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedPrintHistoryRouteImport } from './routes/_authenticated/print-history'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated/templates'
import { Route as VerifyTokenRouteImport } from './routes/verify.$token'
import { Route as AuthenticatedDesignerTemplateIdRouteImport } from './routes/_authenticated/designer.$templateId'
import { Route as AuthenticatedIdCardsIndexRouteImport } from './routes/_authenticated/id-cards.index'
import { Route as AuthenticatedIdCardsCreateRouteImport } from './routes/_authenticated/id-cards.create'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCardSizesRoute = AuthenticatedCardSizesRouteImport.update({
  id: '/card-sizes',
  path: '/card-sizes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrintHistoryRoute =
  AuthenticatedPrintHistoryRouteImport.update({
    id: '/print-history',
    path: '/print-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const VerifyTokenRoute = VerifyTokenRouteImport.update({
  id: '/verify/$token',
  path: '/verify/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDesignerTemplateIdRoute =
  AuthenticatedDesignerTemplateIdRouteImport.update({
    id: '/designer/$templateId',
    path: '/designer/$templateId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIdCardsIndexRoute =
  AuthenticatedIdCardsIndexRouteImport.update({
    id: '/id-cards/',
    path: '/id-cards/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIdCardsCreateRoute =
  AuthenticatedIdCardsCreateRouteImport.update({
    id: '/id-cards/create',
    path: '/id-cards/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/card-sizes': typeof AuthenticatedCardSizesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/print-history': typeof AuthenticatedPrintHistoryRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/designer/$templateId': typeof AuthenticatedDesignerTemplateIdRoute
  '/id-cards/create': typeof AuthenticatedIdCardsCreateRoute
  '/id-cards/': typeof AuthenticatedIdCardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/card-sizes': typeof AuthenticatedCardSizesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/print-history': typeof AuthenticatedPrintHistoryRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/designer/$templateId': typeof AuthenticatedDesignerTemplateIdRoute
  '/id-cards/create': typeof AuthenticatedIdCardsCreateRoute
  '/id-cards': typeof AuthenticatedIdCardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/card-sizes': typeof AuthenticatedCardSizesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/print-history': typeof AuthenticatedPrintHistoryRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/verify/$token': typeof VerifyTokenRoute
  '/_authenticated/designer/$templateId': typeof AuthenticatedDesignerTemplateIdRoute
  '/_authenticated/id-cards/create': typeof AuthenticatedIdCardsCreateRoute
  '/_authenticated/id-cards/': typeof AuthenticatedIdCardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/card-sizes'
    | '/dashboard'
    | '/print-history'
    | '/templates'
    | '/verify/$token'
    | '/designer/$templateId'
    | '/id-cards/create'
    | '/id-cards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/card-sizes'
    | '/dashboard'
    | '/print-history'
    | '/templates'
    | '/verify/$token'
    | '/designer/$templateId'
    | '/id-cards/create'
    | '/id-cards'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/card-sizes'
    | '/_authenticated/dashboard'
    | '/_authenticated/print-history'
    | '/_authenticated/templates'
    | '/verify/$token'
    | '/_authenticated/designer/$templateId'
    | '/_authenticated/id-cards/create'
    | '/_authenticated/id-cards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  VerifyTokenRoute: typeof VerifyTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/card-sizes': {
      id: '/_authenticated/card-sizes'
      path: '/card-sizes'
      fullPath: '/card-sizes'
      preLoaderRoute: typeof AuthenticatedCardSizesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/print-history': {
      id: '/_authenticated/print-history'
      path: '/print-history'
      fullPath: '/print-history'
      preLoaderRoute: typeof AuthenticatedPrintHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/verify/$token': {
      id: '/verify/$token'
      path: '/verify/$token'
      fullPath: '/verify/$token'
      preLoaderRoute: typeof VerifyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/designer/$templateId': {
      id: '/_authenticated/designer/$templateId'
      path: '/designer/$templateId'
      fullPath: '/designer/$templateId'
      preLoaderRoute: typeof AuthenticatedDesignerTemplateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/id-cards/': {
      id: '/_authenticated/id-cards/'
      path: '/id-cards'
      fullPath: '/id-cards/'
      preLoaderRoute: typeof AuthenticatedIdCardsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/id-cards/create': {
      id: '/_authenticated/id-cards/create'
      path: '/id-cards/create'
      fullPath: '/id-cards/create'
      preLoaderRoute: typeof AuthenticatedIdCardsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCardSizesRoute: typeof AuthenticatedCardSizesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPrintHistoryRoute: typeof AuthenticatedPrintHistoryRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
  AuthenticatedDesignerTemplateIdRoute: typeof AuthenticatedDesignerTemplateIdRoute
  AuthenticatedIdCardsCreateRoute: typeof AuthenticatedIdCardsCreateRoute
  AuthenticatedIdCardsIndexRoute: typeof AuthenticatedIdCardsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCardSizesRoute: AuthenticatedCardSizesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPrintHistoryRoute: AuthenticatedPrintHistoryRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
  AuthenticatedDesignerTemplateIdRoute: AuthenticatedDesignerTemplateIdRoute,
  AuthenticatedIdCardsCreateRoute: AuthenticatedIdCardsCreateRoute,
  AuthenticatedIdCardsIndexRoute: AuthenticatedIdCardsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  VerifyTokenRoute: VerifyTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
